server {
  listen 80;
  server_name "apasser.xyz www.apasser.xyz";
  rewrite ^(.*)$ https://${server_name}$1 permanent;
}

server {
  listen 443 ssl;
  server_name "apasser.xyz www.apasser.xyz";

  ssl_certificate /etc/nginx/apasser.xyz.crt;
  ssl_certificate_key /etc/nginx/apasser.xyz.key;
  ssl_prefer_server_ciphers on;

  location / {
    root /blog;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}
